services:

  AdminFrontend:
    image: docker-adminfront
    build:
      context: ./AdminFrontend
      dockerfile: Dockerfile
    ports:
     - "4242:4242"

  mongodb:
    image: mongodb-replicaset
    build:
      context: ./mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGODB_HOSTNAME=mongodb
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_DATABASE=admin
      - COMMON_DATABASE=mydb
      - COMMON_USERNAME=test
      - COMMON_PASSWORD=test
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u $$COMMON_USERNAME -p $$COMMON_PASSWORD \"mongodb://$${MONGODB_HOSTNAME}\" || exit 1"]
      interval: 20s
      timeout: 2s
      retries: 3
    
  BackEnd:
    depends_on:
        mongodb:
          condition: service_healthy
    image: docker-backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://test:test@mongodb:27017
    ports:
      - "8080:8080"

  Getmodul:
    image: docker-genmodul
    build:
      context: ./GenModul
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

volumes:
  mongo_data: