services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  BackEnd:
    image: docker-backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"

volumes:
  mongo_data: